[project]
name = "omero-iviewer"
description="A Python plugin for OMERO.web"
authors = [ 
        {name = "The Open Microscopy Team", email = "ome-devel@lists.openmicroscopy.org.uk"},
        ]
readme = "../README.rst"
requires-python = ">=3.8"
license = {text = "GPL-3.0"}
classifiers = [
          'Development Status :: 5 - Production/Stable',
          'Environment :: Web Environment',
          'Framework :: Django',
          'Intended Audience :: End Users/Desktop',
          'Intended Audience :: Science/Research',
          'Natural Language :: English',
          'Operating System :: OS Independent',
          'Programming Language :: JavaScript',
          'Programming Language :: Python :: 3',
          'Topic :: Internet :: WWW/HTTP',
          'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
          'Topic :: Internet :: WWW/HTTP :: WSGI',
          'Topic :: Scientific/Engineering :: Visualization',
          'Topic :: Software Development :: Libraries :: ',
          'Application Frameworks',
          'Topic :: Text Processing :: Markup :: HTML'
        ]
dependencies = [
    "omero-web>=5.7.0",
]

dynamic = ["version"]

[build-system]
requires = ["setuptools", "setuptools-scm"]
